# Generated by Django 2.0.3 on 2018-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repodetails',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
