# Generated by Django 2.0.3 on 2018-04-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhub', '0002_repodetails_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repodetails',
            name='vcs_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
