# Generated by Django 2.0.3 on 2018-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhub', '0003_repodetails_vcs_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repodetails',
            name='vcs_url',
            field=models.CharField(max_length=500),
        ),
    ]
