# Generated by Django 2.0.3 on 2018-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhub', '0004_auto_20180403_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='repodetails',
            name='git_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repodetails',
            name='github_project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
