# Generated by Django 2.0.3 on 2018-04-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhub', '0005_auto_20180404_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repodetails',
            name='git_username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repodetails',
            name='github_project_name',
            field=models.CharField(max_length=255),
        ),
    ]
